 const weaponList = [
	{name: 'Medium Pistol', price: 50},
  {name: 'Heavy Pistol or Very Heavy Pistol', price: 100},
  {name: 'SMG', price: 100},
  {name: 'Heavy SMG', price:100},
  {name: 'Shotgun', price: 500},
  {name: 'Assault Rifle', price: 500},
  {name: 'Sniper Rifle', price: 500},
  {name: 'Bows or Crossbow', price: 100},
  {name: 'Grenade Launcher or Rocket Launcher', price: 500},
  {name: 'Light Melee Weapon', price: 50},
  {name: 'Medium Melee Weapon', price: 50},
  {name: 'Heavy Melee Weapon', price: 100},
  {name: 'Very Heavy Melee Weapon', price: 100},
  {name: 'A single Exotic Weapon of GM\'s choice' , price: 0},
  {name: 'Armor of 100eb or less', price: 100},
  {name: 'Armor of exactly 500eb', price: 500},
  {name: 'Armor of exactly 1000eb', price: 100},
  {name: 'Ammunition of 500eb or less' , price: 500},
  {name: 'Weapon Attachments of 100eb or less', price: 100},
  {name: 'Weapon Attachments of 500eb or higher', price: 500},
];

const foodList = [
  { name: 'Canned Goods', price: 10 },
  { name: 'Packaged goods', price: 10 },
  { name: 'Frozen Goods', price: 10 },
  { name: 'Bags of Grain', price: 20 },
  { name: 'Kibble Pack', price: 10 },
  { name: 'Bags of Prepak', price: 20 },
  { name: 'Street Drugs of 20eb or less', price: 20 },
  { name: 'Poor Quality Alcohol', price: 10 },
  { name: 'Alcohol', price: 20 },
  { name: 'Excellent Quality Alcohol', price: 100 },
  { name: 'MRE', price: 10 },
  { name: 'Live Chicken', price: 50 },
  { name: 'Live Fish', price: 50 },
  { name: 'Fresh Fruits', price: 50 },
  { name: 'Fresh Vegetables', price: 50 },
  { name: 'Root Vegetables', price: 20 },
  { name: 'Live Pigs', price: 100 },
  { name: 'Exotic Fruits', price: 100 },
  { name: 'Exotic Vegetables', price: 100 },
  { name: 'Street Drugs of exactly 50eb', price: 50 }
];

const cyberwareList = [
  { name: 'Cybereye', price: 100 },
  { name: 'Cyberaudio Suite', price: 500 },
  { name: 'Neural Link', price: 500 },
  { name: 'Cyberarm', price: 500 },
  { name: 'Cyberleg', price: 100 },
  { name: 'External Cyberware of exactly 1000eb', price: 1000 },
  { name: 'External Cyberware of 500eb or less', price: 500 },
  { name: 'Internal Cyberware of exactly 1000eb', price: 1000 },
  { name: 'Internal Cyberware of 500eb or less', price: 500 },
  { name: 'Cybereye Option of exactly 1000eb', price: 1000 },
  { name: 'Cybereye Option of 500eb or less', price: 500 },
  { name: 'Cyberaudio Option of exactly 1000eb', price: 1000 },
  { name: 'Cyberaudio Option of 500eb or less', price: 500 },
  { name: 'Neuralware Option of exactly 1000eb', price: 1000 },
  { name: 'Neuralware Option of 500eb or less', price: 500 },
  { name: 'Cyberlimb Option of exactly 1000eb', price: 1000 },
  { name: 'Cyberlimb Option of 500eb or less', price: 500 },
  { name: "Fashionware of GM's Choice", price: null },
  { name: "Borgware of GM's Choice", price: null },
  { name: "Any Cyberware of GM's Choice", price: null }
];

const electronicList = [
  { name: 'Agent', price: 100 },
  { name: 'Programs or Hardware of 100eb or less', price: 100 },
  { name: 'Audio Recorder', price: 100 },
  { name: 'Bug Detector', price: 500 },
  { name: 'Chemical Analyzer', price: 1000 },
  { name: 'Computer', price: 50 },
  { name: 'Cyberdeck', price: 500 },
  { name: 'Disposable Cell Phone', price: 50 },
  { name: 'Electric Guitar or Other Instrument', price: 500 },
  { name: 'Programs or Hardware of exactly 500eb', price: 500 },
  { name: 'Medscanner', price: 1000 },
  { name: 'Homing Tracer', price: 500 },
  { name: 'Radio Communicator', price: 100 },
  { name: 'Techscanner', price: 1000 },
  { name: 'Smart Glasses', price: 500 },
  { name: 'Radar Detector', price: 500 },
  { name: 'Scrambler/Descrambler', price: 500 },
  { name: 'Radio Scanner/Music Player', price: 50 },
  { name: 'Braindance Viewer', price: 1000 },
  { name: 'Virtuality Goggles', price: 100 }
]

const clothesList = [
  { name: 'Bag Lady Chic', price: null },
  { name: 'Gang Colors', price: null },
  { name: 'Generic Chic', price: null },
  { name: 'Bohemian', price: null },
  { name: 'Leisurewear', price: null },
  { name: 'Nomad Leather', price: null },
  { name: 'Asia Pop', price: null },
  { name: 'Urban Flash', price: null },
  { name: 'Businesswear', price: null },
  { name: 'High Fashion', price: null },
  { name: 'Biomonitor', price: 100 },
  { name: 'Chemskin', price: 100 },
  { name: 'EMP Threading', price: 10 },
  { name: 'Light Tatoo', price: 100 },
  { name: 'Shift Tacts', price: 100 },
  { name: 'Skinwatch', price: 100 },
  { name: 'Techhair', price: 100 },
  { name: 'Generic Chic', price: null },
  { name: 'Leisurewear', price: null },
  { name: 'Gang Colors', price: null },
];

const survivalList = [
  { name: 'Anti-Smog Breathing Mask', price: 20 },
  { name: 'Auto-Level Dampening Ear Protectors', price: 1000 },
  { name: 'Binoculars', price: 50 },
  { name: 'Carryall', price: 20 },
  { name: 'Flashlight', price: 20 },
  { name: 'Duct Tape', price: 20 },
  { name: 'Inflatable Bed & Sleep-bag', price: 20 },
  { name: 'Lock-Picking Set', price: 20 },
  { name: 'Handcuffs', price: 50 },
  { name: 'Medtech Bag', price: 100 },
  { name: 'Tent and Camping Equipment', price: 50 },
  { name: 'Rope (60m)', price: 6020 },
  { name: 'Techtool', price: 100 },
  { name: 'Personal CarePack', price: 20 },
  { name: 'Radiation Suit', price: 1000 },
  { name: 'Road Flare', price: 10 },
  { name: 'Grapple Gun', price: 100 },
  { name: 'Tech Bag', price: 500 },
  { name: 'Shovel or Axe', price: 50 },
  { name: 'Airhypo', price: 50 },
];

export const marketCategories=[weaponList, foodList, cyberwareList, electronicList, clothesList, survivalList]

// pick one from categories
// roll 1d10 times 
// check list and pick differnt items.
// return